### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by federicotorrielli** [grtcdr/paspio#1]
Hi! Big fan of your works here.
I created for you the AUR package, if it's cool for you, I can maintain it and keep it updated with the versions.
Hope it's fine for you, here's the link: https://aur.archlinux.org/packages/paspio-git/
Federico.

**Comment by grtcdr** [comment]
That's lovely! Thank you so much :)

**Comment by federicotorrielli** [comment]
Nice then :) thank you!

**Comment by grtcdr** [comment]
I just added it to the README.
